name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (Ubuntu/macOS)
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          sudo apt-get update
          sudo apt-get install -y autoconf
          # Any other Ubuntu-specific setup
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          echo "No macOS-specific setup required"
        fi
        
    - name: Generate configure script
      run: |
        if [ -f "configure.ac" ]; then
          autoconf
        else
          echo "configure.ac not found"
          exit 1
        fi
    - name: Run configure
      run: ./configure
    - name: Run make
      run: make
    - name: Run make check
      run: make check
    - name: Run make distcheck
      run: make distcheck

